version: "3.7"

services:
  runner-org:
    image: tobiasfenster/github-runner-windows:2004
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
    environment:
      - GITHUBREPO_OR_ORG=cosmoconsult
      - GITHUBPAT=...

  runner-repo:
    image: tobiasfenster/github-runner-windows:2004
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
    environment:
      - GITHUBREPO_OR_ORG=cosmoconsult/github-runner-windows
      - GITHUBPAT=...
