name: Build image manually

on:
  workflow_dispatch:
    inputs:
      base_version:
        description: "base version for the Docker images"
        default: "windowsservercore-ltsc2022"
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pwd }}

      - name: Build Docker image
        run: docker build -t cosmoconsult/github-runner-windows:${{ github.event.inputs.base_version }} -f Dockerfile --build-arg BASE=${{ github.event.inputs.base_version }} .

      - name: Push Docker image
        run: docker push cosmoconsult/github-runner-windows:${{ github.event.inputs.base_version }}
